#!/usr/bin/env bash


#Get the processor generation
if command -v cpuid &> /dev/null
then
  cpuid -1 | grep "(synth)" | awk '{ for (i=3; i<=NF; i++) { printf $i "_"  } }'
  exit
else
  echo "ERROR"
fi